-- MySQL Script generated by MySQL Workbench
-- 11/27/16 21:55:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema advertising_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `advertising_db` ;

-- -----------------------------------------------------
-- Schema advertising_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `advertising_db` DEFAULT CHARACTER SET utf8 ;
USE `advertising_db` ;

-- -----------------------------------------------------
-- Table `product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product` ;

CREATE TABLE IF NOT EXISTS `product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `ASIN` VARCHAR(255) NOT NULL,
  `Title` VARCHAR(255) NULL,
  `MPN` VARCHAR(255) NULL,
  `Price` VARCHAR(45) NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



-- -----------------------------------------------------
-- Dumping data for table `product`
-- -----------------------------------------------------

INSERT INTO `product` (`product_id`, `ASIN`, `Title`, `MPN`, `Price`) VALUES
(1, 'B019TYEXC8', 'Xbox One 500GB Console - Name Your Game Bundle', ' 5C6-00136', '$299.99'),
(2, 'B00UGBMRQ8', 'Apple MacBook Pro MF839LL/A 13.3-Inch Laptop with Retina Display (2.7 GHz Intel Core i5 Processor, 8 GB RAM, 128 GB Hard Drive, OS X Yosemite)', 'MF839LL/A', '$1,299.00');
